### ISSUE TITLE
how I can increase the memory available for java to use for rightfield

### ISSUE THREAD

**Issue by malcook** [myGrid/RightField#5]
I am using rightfield, but when I try to load a large ontology I get an error about not enough memory. Do you know how I can increase the  @memory available for java to use for rightfield?

**Comment by srobb1** [comment]
Here is the actual error I received:
These are technical details that can be sent to the RightField developers to help diagnose an unexpected problem

The version of RightField is: 0.23

org.semanticweb.owlapi.model.OWLOntologyCreationException: There was an error trying to open the ontology from http://data.bioontology.org/ontologies/CHEBI/download?apikey=a60356cf-603a-4179-90da-e1cc051249b8 - **java.lang.OutOfMemoryError: GC overhead limit exceeded**
	at uk.ac.manchester.cs.owl.semspreadsheets.model.OntologyManager.processOntologyDocumentSourceWithTimeout(OntologyManager.java:455)
	at uk.ac.manchester.cs.owl.semspreadsheets.model.OntologyManager.loadOntology(OntologyManager.java:394)
	at uk.ac.manchester.cs.owl.semspreadsheets.ui.task.LoadRepositoryItemTask.runTask(LoadRepositoryItemTask.java:30)
	at uk.ac.manchester.cs.owl.semspreadsheets.ui.task.LoadRepositoryItemTask.runTask(LoadRepositoryItemTask.java:21)
	at uk.ac.manchester.cs.owl.semspreadsheets.ui.task.TaskManager$CallableTask.call(TaskManager.java:209)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by srobb1** [comment]
I tried downloading and loading the ontology as a test, and here is what I get:

These are technical details that can be sent to the RightField developers to help diagnose an unexpected problem

The version of RightField is: 0.23

org.semanticweb.owlapi.model.OWLOntologyCreationException: There was an error trying to open the ontology from file:/Users/smr/Desktop/chebi.owl - java.lang.**OutOfMemoryError**: GC overhead limit exceeded
	at uk.ac.manchester.cs.owl.semspreadsheets.model.OntologyManager.processOntologyDocumentSourceWithTimeout(OntologyManager.java:455)
	at uk.ac.manchester.cs.owl.semspreadsheets.model.OntologyManager.loadOntology(OntologyManager.java:394)
	at uk.ac.manchester.cs.owl.semspreadsheets.ui.task.LoadOntologyTask.runTask(LoadOntologyTask.java:33)
	at uk.ac.manchester.cs.owl.semspreadsheets.ui.task.LoadOntologyTask.runTask(LoadOntologyTask.java:23)
	at uk.ac.manchester.cs.owl.semspreadsheets.ui.task.TaskManager$CallableTask.call(TaskManager.java:209)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by malcook** [comment]
I had a timeout error loading that over the internet.  

When I downloaded it,  I got "java.lang.OutOfMemoryError: Java heap space"

When I alter the rightfield.sh file and inccrease the -Xmx from 500M to 1G, say, like this:

```
set classpath=%~dp0%
java -Xmx1024M -jar rightfield-bin.jar "%classpath%"
@echo off
if errorlevel = 1 goto Error
goto End
:Error
pause
:End

```

I still get out of memory error - it just takes longer

**Comment by stuzart** [comment]
Hopefully you solved this, but you were increasing the memory correctly. Some large ontologies do require a lot of memory to process using the OWL parsing libraries. A more recent version of RightField uses a much newer version of this library which may be more memory efficient, or you could increase the memory further.

**Comment by memory** [comment]
Speaking as @memory, I support increasing me 🤣

**Comment by stuzart** [comment]
A new version, being prepared today will increase the memory and also the the timeout length
